// 全部 inline style 物件
export const S = {
  loginBg: { minHeight: "100vh", background: "#0f0f0f", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'DM Sans', sans-serif" },
  loginCard: { background: "#1a1a1a", borderRadius: 20, padding: "40px 40px", width: 380, boxShadow: "0 20px 60px rgba(0,0,0,0.5)" },
  loginLogoImg: { width: 200, display: "block", margin: "0 auto 8px", filter: "drop-shadow(0 2px 8px rgba(0,0,0,0.4))" },
  loginSub: { color: "#888", textAlign: "center", marginBottom: 28, marginTop: 4 },
  inputGroup: { marginBottom: 16 },
  label: { display: "block", color: "#aaa", fontSize: 13, marginBottom: 6 },
  input: { width: "100%", background: "#2a2a2a", border: "1px solid #333", borderRadius: 10, padding: "12px 14px", color: "#fff", fontSize: 14, outline: "none", boxSizing: "border-box" },
  loginBtn: { width: "100%", background: "#4ECDC4", color: "#000", border: "none", borderRadius: 10, padding: "14px", fontSize: 16, fontWeight: 700, cursor: "pointer", marginTop: 8 },
  hint: { color: "#555", fontSize: 11, textAlign: "center", marginTop: 16, lineHeight: 1.6 },
  appBg: { minHeight: "100vh", background: "#0f0f0f", fontFamily: "'DM Sans', sans-serif", color: "#fff" },
  header: { display: "flex", alignItems: "center", padding: "12px 20px", background: "#1a1a1a", borderBottom: "1px solid #222" },
  headerLogoImg: { height: 36, flex: "0 0 auto", marginRight: 16 },
  syncBadge: { fontSize: 11, marginRight: 12, whiteSpace: "nowrap" },
  headerUser: { color: "#aaa", fontSize: 14, marginRight: 16, flex: 1 },
  logoutBtn: { background: "transparent", border: "1px solid #444", color: "#aaa", borderRadius: 8, padding: "6px 12px", fontSize: 13, cursor: "pointer" },
  creditBar: { display: "flex", justifyContent: "space-between", padding: "10px 20px", background: "#151515", fontSize: 13, color: "#aaa", borderBottom: "1px solid #222" },
  assistBar: { display: "flex", justifyContent: "space-between", padding: "8px 20px", background: "#121212", fontSize: 12, color: "#888", borderBottom: "1px solid #222" },
  quotaBox: { border: "1px solid", borderRadius: 10, padding: "10px 12px", margin: "0 0 16px" },
  soldOutBanner: { background: "#3a1515", color: "#FF8FA3", padding: "10px 20px", fontSize: 13, textAlign: "center", borderBottom: "1px solid #5a2020" },
  expiryBanner: { background: "#332a0f", color: "#FFB347", padding: "10px 20px", fontSize: 13, textAlign: "center", borderBottom: "1px solid #5a4a1a" },
  tabRow: { display: "flex", borderBottom: "1px solid #222", background: "#151515", overflowX: "auto" },
  tab: { flex: 1, background: "transparent", border: "none", color: "#666", padding: "14px 6px", fontSize: 12, cursor: "pointer", whiteSpace: "nowrap", display: "flex", alignItems: "center", justifyContent: "center", gap: 4 },
  tabActive: { flex: 1, background: "transparent", border: "none", color: "#4ECDC4", padding: "14px 6px", fontSize: 12, cursor: "pointer", borderBottom: "2px solid #4ECDC4", fontWeight: 700, whiteSpace: "nowrap", display: "flex", alignItems: "center", justifyContent: "center", gap: 4 },
  badge: { background: "#4ECDC4", color: "#000", borderRadius: 10, padding: "1px 7px", fontSize: 11, fontWeight: 700 },
  calContainer: { padding: 16 },
  container: { padding: 20 },
  weekNav: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  navBtn: { background: "#2a2a2a", border: "none", color: "#fff", borderRadius: 8, padding: "8px 14px", cursor: "pointer", fontSize: 14 },
  weekLabel: { color: "#aaa", fontSize: 13 },
  gridHint: { color: "#666", fontSize: 11, marginBottom: 10 },
  scaleRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  scaleLabel: { fontSize: 11, color: "#888", marginRight: 2 },
  scaleBtn: { background: "#2a2a2a", border: "1px solid #333", color: "#aaa", borderRadius: 8, padding: "4px 10px", fontSize: 11, cursor: "pointer" },
  scaleBtnActive: { background: "#4ECDC4", border: "1px solid #4ECDC4", color: "#000", borderRadius: 8, padding: "4px 10px", fontSize: 11, cursor: "pointer", fontWeight: 700 },
  scaleSlider: { flex: 1, minWidth: 80, maxWidth: 140, accentColor: "#4ECDC4" },
  calScroll: { overflowX: "auto", borderRadius: 12, border: "1px solid #222", maxHeight: "60vh", overflowY: "auto" },
  table: { width: "100%", borderCollapse: "collapse", minWidth: 600 },
  thTime: { width: 50, position: "sticky", left: 0, top: 0, zIndex: 4, background: "#1a1a1a" },
  th: { padding: "10px 4px", textAlign: "center", background: "#1a1a1a", borderBottom: "1px solid #222", position: "sticky", top: 0, zIndex: 2 },
  dayLabel: { color: "#888", fontSize: 11 },
  dateLabel: { color: "#fff", fontWeight: 700, fontSize: 16 },
  tdTime: { fontSize: 11, padding: "2px 6px", whiteSpace: "nowrap", position: "sticky", left: 0, zIndex: 1, background: "#0f0f0f" },
  td: { padding: "1px", borderLeft: "1px solid #161616" },
  slotMulti: { display: "flex", gap: 1, minHeight: 30 },
  slotChip: { flex: 1, borderRadius: 3, padding: "2px 3px", display: "flex", alignItems: "center", justifyContent: "space-between", minHeight: 30, minWidth: 0 },
  slotName: { fontSize: 10, fontWeight: 700, color: "#fff" },
  slotNameFull: { fontSize: 9, fontWeight: 700, color: "#fff", lineHeight: 1.1, wordBreak: "break-word", overflow: "hidden" },
  slotLabelBlock: { display: "flex", flexDirection: "column", gap: 1, minWidth: 0, overflow: "hidden" },
  slotTimeFull: { fontSize: 8, color: "#ffffffcc", lineHeight: 1.1, whiteSpace: "nowrap", overflow: "hidden" },
  slotTypeFull: { fontSize: 8, color: "#ffffffaa", lineHeight: 1.1, whiteSpace: "nowrap", overflow: "hidden" },
  slotStudentsFull: { fontSize: 8, color: "#FFE66D", fontWeight: 700, lineHeight: 1.1, wordBreak: "break-word", overflow: "hidden" },
  slotBottomTime: { fontSize: 8, color: "#ffffffaa", lineHeight: 1.1, marginTop: "auto", whiteSpace: "nowrap", overflow: "hidden" },
  cancelSlotBtn: { background: "transparent", border: "none", color: "#fff", cursor: "pointer", fontSize: 10, padding: 0 },
  slotEmpty: { width: "100%", minHeight: 20, background: "#1a1a1a", border: "none", borderRadius: 3, color: "#3a3a3a", fontSize: 13, cursor: "pointer" },
  slotEmptyRO: { minHeight: 20, background: "#1a1a1a", borderRadius: 3 },
  slotAdd: { width: 18, minHeight: 30, background: "#202020", border: "1px dashed #3a3a3a", borderRadius: 3, color: "#6BCB77", fontSize: 12, cursor: "pointer", flexShrink: 0 },
  slotPast: { minHeight: 20, background: "#111", borderRadius: 3 },
  slotDisabled: { minHeight: 20, background: "#141414", borderRadius: 3 },
  slotClosed: { minHeight: 20, background: "#0c0c0c", borderRadius: 3 },
  closedTag: { fontSize: 9, color: "#7a4040", marginTop: 2 },
  todayTag: { fontSize: 9, color: "#4ECDC4", marginTop: 2, fontWeight: 700 },
  kpiRow: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, marginBottom: 24 },
  kpiCard: { background: "#1a1a1a", borderRadius: 12, padding: "18px 12px", textAlign: "center" },
  kpiLabel: { color: "#888", fontSize: 12, marginBottom: 6 },
  kpiBig: { fontSize: 22, fontWeight: 800, color: "#4ECDC4" },
  sectionTitle: { fontSize: 16, fontWeight: 700, marginBottom: 12, color: "#aaa" },
  emptyText: { color: "#555", textAlign: "center", padding: "40px 0" },
  bookingList: { display: "flex", flexDirection: "column", gap: 10 },
  bookingItem: { background: "#1a1a1a", borderRadius: 12, padding: "14px 16px", display: "flex", alignItems: "center", gap: 12 },
  coachStatRow: { background: "#1a1a1a", borderRadius: 12, padding: "12px 14px", display: "flex", alignItems: "center", gap: 10 },
  dot: { width: 10, height: 10, borderRadius: "50%", flexShrink: 0 },
  avatar: { width: 38, height: 38, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 13, color: "#000", flexShrink: 0 },
  bookingCoach: { fontWeight: 600, fontSize: 14 },
  bookingTime: { color: "#666", fontSize: 12, marginTop: 2 },
  revenueNum: { fontWeight: 800, fontSize: 15, color: "#4ECDC4" },
  idTag: { fontSize: 11, color: "#555", marginLeft: 6 },
  plusTag: { fontSize: 12, color: "#6BCB77", marginLeft: 6 },
  soloTag: { fontSize: 10, color: "#4ECDC4", background: "#13302e", padding: "1px 6px", borderRadius: 6, marginLeft: 4 },
  charterTag: { fontSize: 10, color: "#111", background: "#fff", padding: "1px 6px", borderRadius: 6, marginLeft: 4, fontWeight: 700 },
  duoTag: { fontSize: 10, color: "#FFB347", background: "#33260f", padding: "1px 6px", borderRadius: 6, marginLeft: 4 },
  cancelledTag: { fontSize: 10, color: "#FF8FA3", background: "#3a1515", padding: "1px 6px", borderRadius: 6, marginLeft: 4 },
  cancelBtn: { background: "#2a2a2a", border: "none", color: "#FF6B6B", borderRadius: 8, padding: "6px 12px", fontSize: 13, cursor: "pointer" },
  pastTag: { color: "#555", fontSize: 12 },
  lockTag: { color: "#FFB347", fontSize: 12 },
  addBtn: { background: "#4ECDC4", color: "#000", border: "none", borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  creditBtn: { background: "#1d3a2a", border: "none", color: "#6BCB77", borderRadius: 8, padding: "6px 10px", fontSize: 12, cursor: "pointer", whiteSpace: "nowrap" },
  smallBtn: { background: "#2a2a2a", border: "none", color: "#4ECDC4", borderRadius: 8, padding: "6px 10px", fontSize: 12, cursor: "pointer" },
  delBtn: { background: "#2a2a2a", border: "none", color: "#FF6B6B", borderRadius: 8, padding: "6px 10px", fontSize: 12, cursor: "pointer" },
  flexBetween: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  formCard: { background: "#1a1a1a", borderRadius: 12, padding: 20, maxWidth: 360 },
  ledgerTotal: { marginTop: 16, padding: "12px 16px", background: "#1a1a1a", borderRadius: 10, fontWeight: 700, color: "#4ECDC4", textAlign: "right" },
  monthCard: { background: "#1a1a1a", borderRadius: 12, padding: "12px 16px" },
  monthHead: { fontWeight: 700, fontSize: 14, marginBottom: 8, color: "#fff" },
  monthRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "3px 0" },
  monthLabel: { fontSize: 13, color: "#999" },
  classNum: { fontWeight: 700, fontSize: 15, color: "#FFB347" },
  filterRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14 },
  filterWrap: { display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 10 },
  recSummary: { background: "#151515", borderRadius: 8, padding: "8px 12px", fontSize: 13, color: "#4ECDC4", fontWeight: 700, marginBottom: 12 },
  donePill: { fontSize: 10, color: "#888", background: "#222", padding: "1px 6px", borderRadius: 6, marginLeft: 6 },
  recDetail: { marginTop: 8, padding: "8px 10px", background: "#141414", borderRadius: 8, fontSize: 12, color: "#aaa", lineHeight: 1.7 },
  lowWarnBox: { background: "#3a1515", color: "#FF8FA3", borderRadius: 10, padding: "10px 12px", fontSize: 12, marginTop: 12, lineHeight: 1.6 },
  purchaseBreakdown: { background: "#141414", borderRadius: 10, padding: "8px 12px", marginTop: 4, marginBottom: 4, display: "flex", flexDirection: "column", gap: 8 },
  purchaseRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", borderBottom: "1px solid #222", paddingBottom: 8 },
  lowPill: { fontSize: 10, color: "#fff", background: "#FF6B6B", padding: "1px 6px", borderRadius: 6, marginLeft: 6, fontWeight: 700 },
  filterLabel: { fontSize: 13, color: "#aaa" },
  select: { background: "#2a2a2a", border: "1px solid #333", borderRadius: 8, padding: "8px 12px", color: "#fff", fontSize: 13, outline: "none" },
  linkBtn: { background: "transparent", border: "none", color: "#888", fontSize: 12, cursor: "pointer", textDecoration: "underline", padding: "2px 0", marginTop: 2 },
  assistHint: { color: "#666", fontSize: 12, marginTop: 16 },
  amountPreview: { color: "#6BCB77", fontSize: 13, fontWeight: 600, margin: "4px 0 12px" },
  segRow: { display: "flex", gap: 8 },
  checkRow: { display: "flex", gap: 16, marginBottom: 16 },
  studentChipWrap: { display: "flex", gap: 6, flexWrap: "wrap" },
  studentChip: { background: "#2a2a2a", border: "1px solid #333", color: "#ccc", borderRadius: 16, padding: "6px 12px", fontSize: 12, cursor: "pointer" },
  studentChipActive: { background: "#4ECDC4", border: "1px solid #4ECDC4", color: "#000", borderRadius: 16, padding: "6px 12px", fontSize: 12, cursor: "pointer", fontWeight: 700 },
  studentChipDisabled: { background: "#1a1a1a", border: "1px solid #222", color: "#444", borderRadius: 16, padding: "6px 12px", fontSize: 12, cursor: "not-allowed" },
  rosterChip: { display: "inline-flex", alignItems: "center", gap: 6, background: "#2a2a2a", border: "1px solid #333", color: "#ccc", borderRadius: 16, padding: "6px 8px 6px 12px", fontSize: 12 },
  rosterRemoveBtn: { background: "transparent", border: "none", color: "#FF8FA3", cursor: "pointer", fontSize: 12, padding: "0 2px" },
  checkLabel: { display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "#ccc", cursor: "pointer" },
  seg: { flex: 1, background: "#2a2a2a", border: "1px solid #333", color: "#aaa", borderRadius: 10, padding: "10px", cursor: "pointer", fontSize: 14 },
  segActive: { flex: 1, background: "#4ECDC4", border: "1px solid #4ECDC4", color: "#000", borderRadius: 10, padding: "10px", cursor: "pointer", fontSize: 14, fontWeight: 700 },
  segDisabled: { flex: 1, background: "#1a1a1a", border: "1px solid #2a2a2a", color: "#444", borderRadius: 10, padding: "10px", cursor: "not-allowed", fontSize: 14 },
  priceBox: { background: "#222", borderRadius: 10, padding: "12px 14px", margin: "16px 0" },
  priceRow: { display: "flex", justifyContent: "space-between", fontSize: 13, color: "#aaa", padding: "3px 0" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 20 },
  signCanvas: { width: "100%", height: 160, background: "#fff", borderRadius: 10, touchAction: "none", display: "block" },
  signRow: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 6 },
  qrBtn: { background: "#13302e", border: "1px solid #1d3a2a", color: "#4ECDC4", borderRadius: 8, padding: "4px 10px", fontSize: 11, cursor: "pointer", marginTop: 6 },
  signChip: { background: "#2a2a2a", border: "1px solid #333", color: "#FFB347", borderRadius: 12, padding: "4px 10px", fontSize: 11, cursor: "pointer" },
  signedChip: { background: "#13302e", border: "1px solid #1d3a2a", color: "#6BCB77", borderRadius: 12, padding: "4px 10px", fontSize: 11, cursor: "default" },
  modal: { background: "#1a1a1a", borderRadius: 16, padding: "28px 24px", width: 320, textAlign: "center", maxHeight: "85vh", overflowY: "auto" },
  modalTitle: { fontSize: 18, fontWeight: 700, marginBottom: 12 },
  modalText: { color: "#aaa", marginBottom: 20, lineHeight: 1.6 },
  modalBtns: { display: "flex", gap: 12, marginTop: 8 },
  modalCancel: { flex: 1, background: "#2a2a2a", border: "none", color: "#aaa", borderRadius: 10, padding: 12, cursor: "pointer", fontSize: 14 },
  modalConfirm: { flex: 1, background: "#4ECDC4", border: "none", color: "#000", borderRadius: 10, padding: 12, cursor: "pointer", fontSize: 14, fontWeight: 700 },
  toast: { position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", color: "#000", fontWeight: 700, padding: "12px 24px", borderRadius: 30, fontSize: 14, zIndex: 200, boxShadow: "0 4px 20px rgba(0,0,0,0.3)", maxWidth: "90%", textAlign: "center" },
};
